### ISSUE TITLE
question about dataset preprocess

### ISSUE THREAD

**Issue by roseupram** [ispc-lab/LiDAR4D#5]
Hi,

I'm very interested in your work. 
I noticed that the code only uses the sequence `2013_05_28_drive_0000`, and the frame splitting is hard-coded.

My questions are:

1. Are the results in the paper evaluated on `2013_05_28_drive_0000` or all sequences?
2. If they are evaluated on all sequences, how is the frame splitting done?

data/preprocess/generate_rangeview.py, line 73
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/0328ab9b-acd6-4b78-a7ac-2926d681318a)
same file, line 112
![image](https://github.com/ispc-lab/LiDAR4D/assets/59827483/78b90645-f26f-49c9-8673-191deeb95c00)

**Comment by dyfcalid** [comment]
Due to the time-consuming reconstruction, we only selected representative scenes on sequence `2013_05_28_drive_0000` for experiments in the paper, where the static scenes are consistent with LiDAR-NeRF. 
However, the provided code can be easily extended to other scenes or other sequences, depending on your needs.
